### PR TITLE
Detect and accept Sakai's membership response

### PR DESCRIPTION
**Pull request by dnhutchins**

### CODE REVIEW

**Comment by spvickers** [comment]
Thanks for the pull request.  Are you able to direct me to some documentation for this variation on the unofficial memberships service as implemented by Sakai?  Thanks.

**Comment by dnhutchins** [comment]
No documentation aside from the code @ https://github.com/sakaiproject/sakai/blob/master/basiclti/basiclti-blis/src/java/org/sakaiproject/blti/ServiceServlet.java

But I asked Chuck Severance about this:

David Hutchins  11:36 PM
In the response for basic-lis-readmembershipsforcontext are we wrong, or is everybody else wrong? In that the data is structured with the <member> elements inside of <members>, whereas it appears BB/Canvas/Moodle all have them inside of <memberships>.

And he responded with:

Chuck Severance  9:56 AM
The simple answer is you should check both places and accept either one.  :disappointed:  Here is what happened.  Sakai make the extensions first and deployed them for several years.  Then Moodle implemented them the way Sakai did it.  Then folks felt like it should be documented in the IMS web site as a "unofficial spec" - so Stephen Vickers took my spec and moved it onto the IMS web site and "tweaked it".  Then he changed Moodle to the tweaked way and other LMSs who never implemented it - read that unofficial spec and implemented it.   The spec did not go through any review or certification -so I never noticed the change - and-it felt like an stop-gap anyways.  So now, many years later, I can't really change Sakai or I will break those who have been using it  :disappointed:

**Comment by spvickers** [comment]
Thanks for the update.  I have no recollection of ever tweaking the spec and I have never implemented it for Moodle either.  I am not aware of any other LMS which supports this service in its core product and I am surprised that anyone is still using it.  I will take a look at the Sakai code you referenced.  Thanks.

**Comment by dnhutchins** [comment]
No worries, I'm just a middle man trying to get this plugin working with our Sakai instance at UVA. And just wanted to contribute back the tweaks that were needed on our part to get it working for us :)

**Comment by spvickers** [comment]
Thanks for the input.  I have committed an alternative version of the change to accept an enclosing element of either memberships or members, which also adds a fix for reporting the absence of either as an error.

**Pull request closed without merging**
